runtime: python27
threadsafe: true
api_version: 1

env_variables:
  CLOUDSQL_CONNECTION_NAME: 't35db24833ba76815-tp:us-central1:us-central1-istio-release-e-79a693d8-sql'
  CLOUDSQL_HOST: '35.193.234.53'
  CLOUDSQL_USER: 'root'
  CLOUDSQL_PASSWORD: ''
  CLOUDSQL_DB: 'airflow-db'
  GCS_LOGS_BUCKET: 'us-central1-istio-release-e-79a693d8-bucket'

handlers:
- url: /app
  static_dir: app

- url: /.*
  script: main.APP

libraries:
- name: MySQLdb
  version: "latest"
